[tool.poetry]
name = "eeg"
version = "0.1.0"
description = "A package to generate animated visualization for EEG data"
authors = "Yiki Su"
license = "MIT"
readme = "README.md"
documentation = "https://eeg.readthedocs.io/en/latest/"
homepage = "https://github.com/UBC-MDS/simpl_eeg_capstone"
repository = "https://github.com/UBC-MDS/simpl_eeg_capstone"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
